name: pushwoosh_example
description: Demonstrates how to use the pushwoosh plugin.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dependency_overrides:
  pushwoosh_flutter:
    path: ../
    
  pushwoosh_geozones:
    path: ../../pushwoosh_geozones

  pushwoosh_inbox:
    path: ../../pushwoosh_inbox

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
